version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_app
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.2
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: text_classification
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3306:3306"
